# coding: utf-8

"""
    Flat API

    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

    The version of the OpenAPI document: 2.26.0
    Contact: developers@flat.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from flat_api.aio.models.lti_configuration import LtiConfiguration
from flat_api.aio.models.lti_configuration1p3_base_supported_services import LtiConfiguration1p3BaseSupportedServices
from flat_api.aio.models.lti_configuration1p3_base_tool import LtiConfiguration1p3BaseTool
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateLtiConfiguration200Response(LtiConfiguration):
    """
    CreateLtiConfiguration200Response
    """ # noqa: E501
    registration_url: Optional[StrictStr] = Field(default=None, description="One-time registration URL (only for dynamic registration)", alias="registrationUrl")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "ltiVersion", "organizationId", "organizationName", "creatorId", "creationDate", "lastUsedDate", "status", "consumerKey", "consumerSecret", "lms", "name", "tool", "mode", "platformIss", "platformName", "clientId", "deploymentId", "accessTokenUrl", "authorizationUrl", "jwksUrl", "deploymentMode", "supportedServices", "publicKeysetUrl", "initiateLoginUrl", "redirectUris", "enableEmailMatching", "parentId", "deploymentKey", "deploymentBreakdownBy", "deploymentBreakdownId", "registrationToken", "registrationUrl", "registrationTokenUsed", "registrationCompletionDate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateLtiConfiguration200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tool
        if self.tool:
            _dict['tool'] = self.tool.to_dict()
        # override the default output from pydantic by calling `to_dict()` of supported_services
        if self.supported_services:
            _dict['supportedServices'] = self.supported_services.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if last_used_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_date is None and "last_used_date" in self.model_fields_set:
            _dict['lastUsedDate'] = None

        # set to None if registration_completion_date (nullable) is None
        # and model_fields_set contains the field
        if self.registration_completion_date is None and "registration_completion_date" in self.model_fields_set:
            _dict['registrationCompletionDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateLtiConfiguration200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "ltiVersion": obj.get("ltiVersion"),
            "organizationId": obj.get("organizationId"),
            "organizationName": obj.get("organizationName"),
            "creatorId": obj.get("creatorId"),
            "creationDate": obj.get("creationDate"),
            "lastUsedDate": obj.get("lastUsedDate"),
            "status": obj.get("status"),
            "consumerKey": obj.get("consumerKey"),
            "consumerSecret": obj.get("consumerSecret"),
            "lms": obj.get("lms"),
            "name": obj.get("name"),
            "tool": LtiConfiguration1p3BaseTool.from_dict(obj["tool"]) if obj.get("tool") is not None else None,
            "mode": obj.get("mode"),
            "platformIss": obj.get("platformIss"),
            "platformName": obj.get("platformName"),
            "clientId": obj.get("clientId"),
            "deploymentId": obj.get("deploymentId"),
            "accessTokenUrl": obj.get("accessTokenUrl"),
            "authorizationUrl": obj.get("authorizationUrl"),
            "jwksUrl": obj.get("jwksUrl"),
            "deploymentMode": obj.get("deploymentMode"),
            "supportedServices": LtiConfiguration1p3BaseSupportedServices.from_dict(obj["supportedServices"]) if obj.get("supportedServices") is not None else None,
            "publicKeysetUrl": obj.get("publicKeysetUrl"),
            "initiateLoginUrl": obj.get("initiateLoginUrl"),
            "redirectUris": obj.get("redirectUris"),
            "enableEmailMatching": obj.get("enableEmailMatching") if obj.get("enableEmailMatching") is not None else True,
            "parentId": obj.get("parentId"),
            "deploymentKey": obj.get("deploymentKey"),
            "deploymentBreakdownBy": obj.get("deploymentBreakdownBy"),
            "deploymentBreakdownId": obj.get("deploymentBreakdownId"),
            "registrationToken": obj.get("registrationToken"),
            "registrationUrl": obj.get("registrationUrl"),
            "registrationTokenUsed": obj.get("registrationTokenUsed"),
            "registrationCompletionDate": obj.get("registrationCompletionDate")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


