# coding: utf-8

"""
    Flat API

    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

    The version of the OpenAPI document: 2.26.0
    Contact: developers@flat.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from flat_api.aio.models.score_creation_builder_data_all_of_builder_data_score_data_instruments import ScoreCreationBuilderDataAllOfBuilderDataScoreDataInstruments
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScoreCreationBuilderDataAllOfBuilderDataScoreData(BaseModel):
    """
    ScoreCreationBuilderDataAllOfBuilderDataScoreData
    """ # noqa: E501
    use_tab_staff: Optional[StrictBool] = Field(default=None, description="true if the TAB staff is displayed with fretted instruments", alias="useTabStaff")
    use_chord_grid: Optional[StrictBool] = Field(default=None, description="true if the chord grid must be displayed with fretted instruments", alias="useChordGrid")
    fifths: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The key signature of the score (expressed between -7 and 7). Major C is used when the value is not provided.")
    nb_beats: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of beats in the measure", alias="nbBeats")
    beat_type: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The duration of a beat in the measure", alias="beatType")
    instruments: List[ScoreCreationBuilderDataAllOfBuilderDataScoreDataInstruments] = Field(description="The list of instruments to add to the score. See the [Instrument IDs reference](https://flat.io/developers/docs/api/instruments) for the possible values for `group` and `instrument` (also available as the [`@flat/instruments`](https://www.npmjs.com/package/@flat/instruments) package). ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["useTabStaff", "useChordGrid", "fifths", "nbBeats", "beatType", "instruments"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScoreCreationBuilderDataAllOfBuilderDataScoreData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instruments (list)
        _items = []
        if self.instruments:
            for _item_instruments in self.instruments:
                if _item_instruments:
                    _items.append(_item_instruments.to_dict())
            _dict['instruments'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScoreCreationBuilderDataAllOfBuilderDataScoreData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "useTabStaff": obj.get("useTabStaff"),
            "useChordGrid": obj.get("useChordGrid"),
            "fifths": obj.get("fifths"),
            "nbBeats": obj.get("nbBeats"),
            "beatType": obj.get("beatType"),
            "instruments": [ScoreCreationBuilderDataAllOfBuilderDataScoreDataInstruments.from_dict(_item) for _item in obj["instruments"]] if obj.get("instruments") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


