# coding: utf-8

"""
    Flat API

    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html)   # noqa: E501

    The version of the OpenAPI document: 2.18.0
    Contact: developers@flat.io
    Generated by: https://openapi-generator.tech
"""

from flat_api.paths.classes_class_activate.post import ActivateClass
from flat_api.paths.classes_class_users_user.put import AddClassUser
from flat_api.paths.classes_class_assignments_assignment_archive.post import ArchiveAssignment
from flat_api.paths.classes_class_archive.post import ArchiveClass
from flat_api.paths.classes_class_assignments_assignment_copy.post import CopyAssignment
from flat_api.paths.classes.post import CreateClass
from flat_api.paths.classes_class_assignments.post import CreateClassAssignment
from flat_api.paths.classes_class_assignments_assignment_submissions.put import CreateSubmission
from flat_api.paths.classes_class_test_student.post import CreateTestStudentAccount
from flat_api.paths.classes_class_users_user.delete import DeleteClassUser
from flat_api.paths.classes_class_assignments_assignment_submissions_submission.delete import DeleteSubmission
from flat_api.paths.classes_class_assignments_assignment_submissions_submission_comments_comment.delete import DeleteSubmissionComment
from flat_api.paths.classes_class_assignments_assignment_submissions_submission.put import EditSubmission
from flat_api.paths.classes_enroll_enrollment_code.post import EnrollClass
from flat_api.paths.classes_class_assignments_assignment_submissions_csv.get import ExportSubmissionsReviewsAsCsv
from flat_api.paths.classes_class_assignments_assignment_submissions_excel.get import ExportSubmissionsReviewsAsExcel
from flat_api.paths.classes_class.get import GetClass
from flat_api.paths.scores_score_submissions.get import GetScoreSubmissions
from flat_api.paths.classes_class_assignments_assignment_submissions_submission.get import GetSubmission
from flat_api.paths.classes_class_assignments_assignment_submissions_submission_comments.get import GetSubmissionComments
from flat_api.paths.classes_class_assignments_assignment_submissions_submission_history.get import GetSubmissionHistory
from flat_api.paths.classes_class_assignments_assignment_submissions.get import GetSubmissions
from flat_api.paths.classes_class_assignments.get import ListAssignments
from flat_api.paths.classes_class_students_user_submissions.get import ListClassStudentSubmissions
from flat_api.paths.classes.get import ListClasses
from flat_api.paths.classes_class_assignments_assignment_submissions_submission_comments.post import PostSubmissionComment
from flat_api.paths.classes_class_assignments_assignment_archive.delete import UnarchiveAssignment
from flat_api.paths.classes_class_archive.delete import UnarchiveClass
from flat_api.paths.classes_class.put import UpdateClass
from flat_api.paths.classes_class_assignments_assignment_submissions_submission_comments_comment.put import UpdateSubmissionComment


class ModelClassApi(
    ActivateClass,
    AddClassUser,
    ArchiveAssignment,
    ArchiveClass,
    CopyAssignment,
    CreateClass,
    CreateClassAssignment,
    CreateSubmission,
    CreateTestStudentAccount,
    DeleteClassUser,
    DeleteSubmission,
    DeleteSubmissionComment,
    EditSubmission,
    EnrollClass,
    ExportSubmissionsReviewsAsCsv,
    ExportSubmissionsReviewsAsExcel,
    GetClass,
    GetScoreSubmissions,
    GetSubmission,
    GetSubmissionComments,
    GetSubmissionHistory,
    GetSubmissions,
    ListAssignments,
    ListClassStudentSubmissions,
    ListClasses,
    PostSubmissionComment,
    UnarchiveAssignment,
    UnarchiveClass,
    UpdateClass,
    UpdateSubmissionComment,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
