# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from flat_api.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    ME = "/me"
    SCORES = "/scores"
    SCORES_SCORE = "/scores/{score}"
    SCORES_SCORE_UNTRASH = "/scores/{score}/untrash"
    SCORES_SCORE_SUBMISSIONS = "/scores/{score}/submissions"
    SCORES_SCORE_FORK = "/scores/{score}/fork"
    SCORES_SCORE_COLLABORATORS = "/scores/{score}/collaborators"
    SCORES_SCORE_COLLABORATORS_COLLABORATOR = "/scores/{score}/collaborators/{collaborator}"
    SCORES_SCORE_TRACKS = "/scores/{score}/tracks"
    SCORES_SCORE_TRACKS_TRACK = "/scores/{score}/tracks/{track}"
    SCORES_SCORE_COMMENTS = "/scores/{score}/comments"
    SCORES_SCORE_COMMENTS_COMMENT = "/scores/{score}/comments/{comment}"
    SCORES_SCORE_COMMENTS_COMMENT_RESOLVED = "/scores/{score}/comments/{comment}/resolved"
    SCORES_SCORE_REVISIONS = "/scores/{score}/revisions"
    SCORES_SCORE_REVISIONS_REVISION = "/scores/{score}/revisions/{revision}"
    SCORES_SCORE_REVISIONS_REVISION_FORMAT = "/scores/{score}/revisions/{revision}/{format}"
    SCORES_SCORE_REVISIONS_REVISION_FORMAT_TASK = "/scores/{score}/revisions/{revision}/{format}/task"
    COLLECTIONS = "/collections"
    COLLECTIONS_COLLECTION = "/collections/{collection}"
    COLLECTIONS_COLLECTION_UNTRASH = "/collections/{collection}/untrash"
    COLLECTIONS_COLLECTION_SCORES = "/collections/{collection}/scores"
    COLLECTIONS_COLLECTION_SCORES_SCORE = "/collections/{collection}/scores/{score}"
    TASKS_TASK = "/tasks/{task}"
    USERS_USER = "/users/{user}"
    USERS_USER_LIKES = "/users/{user}/likes"
    USERS_USER_SCORES = "/users/{user}/scores"
    ORGANIZATIONS_USERS = "/organizations/users"
    ORGANIZATIONS_USERS_COUNT = "/organizations/users/count"
    ORGANIZATIONS_USERS_USER = "/organizations/users/{user}"
    ORGANIZATIONS_USERS_USER_SIGNIN_LINK = "/organizations/users/{user}/signinLink"
    ORGANIZATIONS_USERS_USER_ACCESS_TOKEN = "/organizations/users/{user}/accessToken"
    ORGANIZATIONS_INVITATIONS = "/organizations/invitations"
    ORGANIZATIONS_INVITATIONS_INVITATION = "/organizations/invitations/{invitation}"
    ORGANIZATIONS_LTI_CREDENTIALS = "/organizations/lti/credentials"
    ORGANIZATIONS_LTI_CREDENTIALS_CREDENTIALS = "/organizations/lti/credentials/{credentials}"
    CLASSES = "/classes"
    CLASSES_CLASS = "/classes/{class}"
    CLASSES_CLASS_ARCHIVE = "/classes/{class}/archive"
    CLASSES_CLASS_ACTIVATE = "/classes/{class}/activate"
    CLASSES_CLASS_USERS_USER = "/classes/{class}/users/{user}"
    CLASSES_CLASS_STUDENTS_USER_SUBMISSIONS = "/classes/{class}/students/{user}/submissions"
    CLASSES_CLASS_ASSIGNMENTS = "/classes/{class}/assignments"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_COPY = "/classes/{class}/assignments/{assignment}/copy"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_ARCHIVE = "/classes/{class}/assignments/{assignment}/archive"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_SUBMISSIONS = "/classes/{class}/assignments/{assignment}/submissions"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_SUBMISSIONS_CSV = "/classes/{class}/assignments/{assignment}/submissions/csv"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_SUBMISSIONS_EXCEL = "/classes/{class}/assignments/{assignment}/submissions/excel"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_SUBMISSIONS_SUBMISSION = "/classes/{class}/assignments/{assignment}/submissions/{submission}"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_SUBMISSIONS_SUBMISSION_HISTORY = "/classes/{class}/assignments/{assignment}/submissions/{submission}/history"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_SUBMISSIONS_SUBMISSION_COMMENTS = "/classes/{class}/assignments/{assignment}/submissions/{submission}/comments"
    CLASSES_CLASS_ASSIGNMENTS_ASSIGNMENT_SUBMISSIONS_SUBMISSION_COMMENTS_COMMENT = "/classes/{class}/assignments/{assignment}/submissions/{submission}/comments/{comment}"
    CLASSES_CLASS_TEST_STUDENT = "/classes/{class}/testStudent"
    CLASSES_ENROLL_ENROLLMENT_CODE = "/classes/enroll/{enrollmentCode}"
    GROUPS_GROUP = "/groups/{group}"
    GROUPS_GROUP_USERS = "/groups/{group}/users"
    GROUPS_GROUP_SCORES = "/groups/{group}/scores"
    EDU_RESOURCES = "/eduResources"
    EDU_RESOURCES_LIBRARIES = "/eduResources/libraries"
    EDU_RESOURCES_RESOURCE = "/eduResources/{resource}"
    EDU_RESOURCES_RESOURCE_MOVE = "/eduResources/{resource}/move"
    EDU_RESOURCES_RESOURCE_COPY = "/eduResources/{resource}/copy"
    EDU_RESOURCES_RESOURCE_COPY_TO_DEMO_CLASS = "/eduResources/{resource}/copyToDemoClass"
    EDU_RESOURCES_RESOURCE_USE_IN_CLASS = "/eduResources/{resource}/useInClass"
    EDU_RESOURCES_RESOURCE_ASSIGNMENT = "/eduResources/{resource}/assignment"
