# coding: utf-8

"""
    Flat API

    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

    The version of the OpenAPI document: 2.26.0
    Contact: developers@flat.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from flat_api.models.lti_configuration_create1p1 import LtiConfigurationCreate1p1
from flat_api.models.lti_configuration_create1p3_deployment import LtiConfigurationCreate1p3Deployment
from flat_api.models.lti_configuration_create1p3_dynamic import LtiConfigurationCreate1p3Dynamic
from flat_api.models.lti_configuration_create1p3_manual import LtiConfigurationCreate1p3Manual
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

LTICONFIGURATIONCREATE_ONE_OF_SCHEMAS = ["LtiConfigurationCreate1p1", "LtiConfigurationCreate1p3Deployment", "LtiConfigurationCreate1p3Dynamic", "LtiConfigurationCreate1p3Manual"]

class LtiConfigurationCreate(BaseModel):
    """
    Request to create a new LTI configuration (unified 1.1 and 1.3)
    """
    # data type: LtiConfigurationCreate1p1
    oneof_schema_1_validator: Optional[LtiConfigurationCreate1p1] = None
    # data type: LtiConfigurationCreate1p3Dynamic
    oneof_schema_2_validator: Optional[LtiConfigurationCreate1p3Dynamic] = None
    # data type: LtiConfigurationCreate1p3Deployment
    oneof_schema_3_validator: Optional[LtiConfigurationCreate1p3Deployment] = None
    # data type: LtiConfigurationCreate1p3Manual
    oneof_schema_4_validator: Optional[LtiConfigurationCreate1p3Manual] = None
    actual_instance: Optional[Union[LtiConfigurationCreate1p1, LtiConfigurationCreate1p3Deployment, LtiConfigurationCreate1p3Dynamic, LtiConfigurationCreate1p3Manual]] = None
    one_of_schemas: Set[str] = { "LtiConfigurationCreate1p1", "LtiConfigurationCreate1p3Deployment", "LtiConfigurationCreate1p3Dynamic", "LtiConfigurationCreate1p3Manual" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = LtiConfigurationCreate.model_construct()
        error_messages = []
        match = 0
        # validate data type: LtiConfigurationCreate1p1
        if not isinstance(v, LtiConfigurationCreate1p1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LtiConfigurationCreate1p1`")
        else:
            match += 1
        # validate data type: LtiConfigurationCreate1p3Dynamic
        if not isinstance(v, LtiConfigurationCreate1p3Dynamic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LtiConfigurationCreate1p3Dynamic`")
        else:
            match += 1
        # validate data type: LtiConfigurationCreate1p3Deployment
        if not isinstance(v, LtiConfigurationCreate1p3Deployment):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LtiConfigurationCreate1p3Deployment`")
        else:
            match += 1
        # validate data type: LtiConfigurationCreate1p3Manual
        if not isinstance(v, LtiConfigurationCreate1p3Manual):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LtiConfigurationCreate1p3Manual`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in LtiConfigurationCreate with oneOf schemas: LtiConfigurationCreate1p1, LtiConfigurationCreate1p3Deployment, LtiConfigurationCreate1p3Dynamic, LtiConfigurationCreate1p3Manual. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in LtiConfigurationCreate with oneOf schemas: LtiConfigurationCreate1p1, LtiConfigurationCreate1p3Deployment, LtiConfigurationCreate1p3Dynamic, LtiConfigurationCreate1p3Manual. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into LtiConfigurationCreate1p1
        try:
            instance.actual_instance = LtiConfigurationCreate1p1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LtiConfigurationCreate1p3Dynamic
        try:
            instance.actual_instance = LtiConfigurationCreate1p3Dynamic.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LtiConfigurationCreate1p3Deployment
        try:
            instance.actual_instance = LtiConfigurationCreate1p3Deployment.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LtiConfigurationCreate1p3Manual
        try:
            instance.actual_instance = LtiConfigurationCreate1p3Manual.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into LtiConfigurationCreate with oneOf schemas: LtiConfigurationCreate1p1, LtiConfigurationCreate1p3Deployment, LtiConfigurationCreate1p3Dynamic, LtiConfigurationCreate1p3Manual. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into LtiConfigurationCreate with oneOf schemas: LtiConfigurationCreate1p1, LtiConfigurationCreate1p3Deployment, LtiConfigurationCreate1p3Dynamic, LtiConfigurationCreate1p3Manual. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], LtiConfigurationCreate1p1, LtiConfigurationCreate1p3Deployment, LtiConfigurationCreate1p3Dynamic, LtiConfigurationCreate1p3Manual]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


